### ISSUE TITLE
build fails due to impossible to resolve depdencies from @vueuse/*

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [3forges/demo-nebulix#2]
The issue when we run the build : 

```bash
Utilisateur@Utilisateur-PC MINGW64 ~/demo-nebulix (jb/pipeline/vercel/deployment)
$ pnpm i && source .env && pnpm run build
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 17, reused 17, downloaded 0, added 0
Progress: resolved 26, reused 26, downloaded 0, added 0
Progress: resolved 28, reused 28, downloaded 0, added 0
Progress: resolved 37, reused 37, downloaded 0, added 0
Progress: resolved 38, reused 38, downloaded 0, added 0
Progress: resolved 39, reused 39, downloaded 0, added 0
Progress: resolved 40, reused 40, downloaded 0, added 0
Progress: resolved 41, reused 40, downloaded 0, added 0
Progress: resolved 65, reused 61, downloaded 0, added 0
Progress: resolved 72, reused 68, downloaded 0, added 0
Progress: resolved 81, reused 77, downloaded 0, added 0
Progress: resolved 89, reused 85, downloaded 0, added 0
Progress: resolved 103, reused 99, downloaded 0, added 0
Progress: resolved 155, reused 151, downloaded 0, added 0
Progress: resolved 169, reused 165, downloaded 0, added 0
Progress: resolved 206, reused 202, downloaded 0, added 0
Progress: resolved 240, reused 234, downloaded 0, added 0
Progress: resolved 274, reused 269, downloaded 0, added 0
Progress: resolved 297, reused 292, downloaded 0, added 0
Progress: resolved 314, reused 309, downloaded 0, added 0
Progress: resolved 358, reused 345, downloaded 0, added 0
Progress: resolved 389, reused 376, downloaded 0, added 0
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
Progress: resolved 422, reused 409, downloaded 0, added 0
Progress: resolved 509, reused 475, downloaded 0, added 0
Progress: resolved 529, reused 495, downloaded 0, added 0
Progress: resolved 589, reused 534, downloaded 0, added 0
 WARN  deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
Progress: resolved 611, reused 556, downloaded 0, added 0
Progress: resolved 623, reused 568, downloaded 0, added 0
Progress: resolved 653, reused 598, downloaded 0, added 0
Progress: resolved 710, reused 650, downloaded 0, added 0
Progress: resolved 787, reused 708, downloaded 0, added 0
Progress: resolved 842, reused 766, downloaded 0, added 0
Progress: resolved 844, reused 768, downloaded 0, added 0
Progress: resolved 849, reused 773, downloaded 0, added 0
Progress: resolved 851, reused 775, downloaded 0, added 0
Progress: resolved 853, reused 777, downloaded 0, added 0
Progress: resolved 855, reused 779, downloaded 0, added 0
Progress: resolved 862, reused 786, downloaded 0, added 0
Progress: resolved 877, reused 801, downloaded 0, added 0
Progress: resolved 888, reused 812, downloaded 0, added 0
Progress: resolved 933, reused 857, downloaded 0, added 0
Progress: resolved 944, reused 866, downloaded 0, added 0
Progress: resolved 952, reused 876, downloaded 0, added 0
Progress: resolved 961, reused 885, downloaded 0, added 0
Progress: resolved 981, reused 892, downloaded 0, added 0
Packages: +894
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 981, reused 894, downloaded 0, added 30, done

dependencies:
+ @astrojs/check 0.3.1
+ @astrojs/mdx 1.1.5
+ @astrojs/prefetch 0.4.1
+ @astrojs/rss 3.0.0
+ @astrojs/sitemap 3.0.3
+ @astrojs/tailwind 5.0.2
+ @astrojs/vue 3.0.4
+ @fontsource-variable/inter-tight 5.0.18
+ @nanostores/vue 0.10.0
+ @panzoom/panzoom 4.5.1
+ @remark-embedder/core 3.0.2
+ @remark-embedder/transformer-oembed 3.0.0
+ @vueuse/components 10.6.1
+ @vueuse/integrations 10.6.1
+ astro 3.6.0
+ astro-compress 2.2.3
+ astro-critters 2.0.11
+ astro-icon 0.8.1
+ astro-imagetools 0.9.0
+ astro-m2dx 0.7.16
+ async-validator 4.2.5
+ body-scroll-lock 4.0.0-beta.0
+ convert 4.14.0
+ js-convert-case 4.2.0
+ marked 10.0.0
+ nanostores 0.9.5
+ rehype-external-links 3.0.0
+ tailwindcss 3.3.5
+ typescript 5.3.2
+ vue 3.3.9
+ vue3-popper 1.5.0
+ vue3-toastify 0.1.14

devDependencies:
+ @tailwindcss/nesting 0.0.0-insiders.565cd3e
+ cross-env 7.0.3
+ dotenv 16.3.1
+ pagefind 1.0.4
+ postcss-import 15.1.0
+ postcss-nesting 12.0.1
+ prettier 3.1.0
+ prettier-plugin-astro 0.12.2
+ prettier-plugin-tailwindcss 0.5.7

 WARN  Issues with peer dependencies found
.
└─┬ astro-compress 2.2.3
  └─┬ typescript-esbuild 0.3.1
    └─┬ typedoc 0.25.2
      └── ✕ unmet peer typescript@"4.6.x || 4.7.x || 4.8.x || 4.9.x || 5.0.x || 5.1.x || 5.2.x": found 5.3.2

Done in 53.9s

> nebulix@0.1.9 build C:\Users\Utilisateur\demo-nebulix
> astro build

16:11:55 [content] Types generated 1.26s
16:11:55 [build] output target: static
16:11:55 [build] Collecting build info...
16:11:55 [build] Completed in 1.46s.
16:11:55 [build] Building static entrypoints...
[vite]: Rollup failed to resolve import "@vueuse/core" from "C:/Users/Utilisateur/demo-nebulix/src/components/shop/SnipCartInit.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
 error   [vite]: Rollup failed to resolve import "@vueuse/core" from "C:/Users/Utilisateur/demo-nebulix/src/components/shop/SnipCartInit.vue".
  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "@vueuse/core" from "C:/Users/Utilisateur/demo-nebulix/src/components/shop/SnipCartInit.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
    at onRollupWarning (file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48248:9)
    at onwarn (file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
    at file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
 ELIFECYCLE  Command failed with exit code 1.

Utilisateur@Utilisateur-PC MINGW64 ~/demo-nebulix (jb/pipeline/vercel/deployment)
$ pnpm i && source .env && pnpm run dev:demo
Lockfile is up to date, resolution step is skipped
Already up to date

Done in 1.2s

> nebulix@0.1.9 dev:demo C:\Users\Utilisateur\demo-nebulix
> cross-env BLOG_SLUG=blog PORTFOLIO_SLUG=work SHOP_SLUG=shop MENU_SLUG=menu WEBSITE_LANGUAGE=en CURRENCY=USD UNITS=metric NODE_VERSION=18 SNIPCART_KEY=ZDVjZmQwYmUtMzNlYy00OGEyLTkxMTItMTg4YTI5NGQxN2I3NjM4MjgzOTQyMzA2MTM1NjI1 astro dev

   astro  v3.6.0 started in 1753ms

  ┃ Local    http://localhost:4321/
  ┃ Network  use --host to expose

16:32:38 [content] Watching src/content/ for changes
Error: The following dependencies are imported but could not be resolved:

  @vueuse/core (imported by C:/Users/Utilisateur/demo-nebulix/src/components/common/ContactDialog.vue?id=0)

Are they installed?
    at file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:45779:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/Utilisateur/demo-nebulix/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:45187:38
16:32:39 [content] Types generated
16:32:39 [astro] update /.astro/types.d.ts

```

* Now, I have found a commit where they last week made a major upgrade, which probably introduced the regression of the build process : https://github.com/unfolding-io/nebulix/commit/224cc089e27ed21f637931fa5d7eac34332ad057
* build : 
```bash
git checkout 224cc089e27ed21f637931fa5d7eac34332ad057

```

**Comment by Jean-Baptiste-Lasselle** [comment]
* https://github.com/slidevjs/slidev/issues/410
* https://github.com/vueuse/vueuse/issues/2972
